### ISSUE TITLE
Upload API Error for large files

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#111]
The upload works with small files but does not work for big files. As an a example it does not work with a geotiff of 150Mb. 
This may be also the reason why the client lib does not work.

**Comment by kr1zz** [comment]
The upload failed due to a bug in the client (headers were not well formatted), @sergin13 and I solved it earlier (see [commit 597bb59](https://github.com/fadeoutsoftware/WASDI/commit/597bb5985e516e298cdf1d4def4e952c48b57137)). The change still need to be published, but it runs smoothly (I managed to upload a 3.19 GB file to wasdi.net) running the client locally.

**Comment by kr1zz** [comment]
Test results:

- official server: transfered a 3.82 GB-large w/o problems (except the time it took...)
- development server: still broken with large files, but transfers small files. Connection reset from the server side (maybe the server needs some maintenance?)

**Comment by kr1zz** [comment]
One more question: do we really need to launch the ingest as an asynch operation? The time-consuming operation is the upload, once it's done can't we just add the file to the workspace and update the DB without delaying any further the completion?
