### ISSUE TITLE
Rotate envi.log

### ISSUE THREAD

**Issue by kr1zz** [fadeoutsoftware/WASDI#147]
The log grows quickly, we should automate its rotation

**Comment by wasdi-sysadmin-br** [comment]
**Update:**

I did a quick analysis: this log is normally rotated because we have a configuration file.
I think it doesn't work because of the reason explained in the ticket #332 

A test is ongoing for #332 : if it works, probably this rotation will work.
So we have to wait the result of ongoing test before to process this ticket.

**Comment by wasdi-sysadmin-br** [comment]
**Update:**

All problems was fixed in #332 
Now I will ask to Cristiano if the configuration made answer to his expectations
