### ISSUE TITLE
Update Logger in projects

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#233]
We need to move to log4j 2.
http://logging.apache.org/log4j/log4j-2.0-beta7/manual/migration.html

https://stackoverflow.com/questions/28349309/how-can-i-change-the-default-location-of-log4j2-xml-in-java-spring-boot/59190560#59190560

**Comment by wasdi-sysadmin-br** [comment]
When we will work on this ticket, maybe we can profite to analyze to change the appender in use: currently we have RollingFileAppender which is in conflit with Logrotate.

To fix we have 3 possibilities:
  - to keep only the internal rotation system RollingFileAppender  (-> we remove the logrotate configuration file)
  - to switch on logrotate only keeping a file appender (-> we replace RollingFileAppender with FileAppender)
  - to switch on logrotate only using a syslog mechanism: instead of to produce the file directly we produce the file through syslog

And last point: I think we should review the file utils/log4j.xml because I suspect a wrong configuration as we configured 2 files not related to dbUtils : launcher.log + publisher.log
