### ISSUE TITLE
Online log view: control if the timer to refresh log is deleted when closed

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#238]
From different test it happens to have many logs requested also when the log view window is closed.
Control if the timer is really destroyed when the window is closed to avoid useless traffic.

**Comment by mmenapace** [comment]
The problem is related to the dialog view ProcessErrorLogsDialogView.html
The related controller, ProcessErrorLogsDialogController.js, creates a timer to update the logs content
on a 5 seconds interval. 
The controller ends up in flooding the server with a lot of spurious  and resource effective requests, 
even if the dialog is closed.
