### ISSUE TITLE
Workspace Processes List: add automatic update

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#316]
The Workspace Processes List dialog view on the client does not refresh the info. We should add also there a timer to refresh processes percentage, status and time.

**Comment by mmenapace** [comment]
Proposal :
Instead of an automatic update based on a fixed amount of time, shouldn't be also valid let the user trigger the update?
This will permit to save resources implied in a set of asynchronous calls.
The timer mechanism, on the client side, can be used to idle the update requests for a fixed amount of time after an update asynchronous response is received.
