### ISSUE TITLE
Recover Password: give feedback and does not work for 2.0

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#328]
When the user tries to recover a password the client does not give any feedback in the interface.
Then it looks that this is working for old auth but not for the new one.

**Comment by mmenapace** [comment]
Tested reset password:
- Legacy version does not work because of a "data.data" already known issue in the deployed version of home controller. Already fixed in develop. Will be fixed on following releases/updates.
- New version, that relies on keycloak, works fine from wasdi.net.
Worked on graphical aspect on branch fix/resetPasswordUI : 
started working from develop
updated messages and UI behaviour

**Comment by mmenapace** [comment]
deployed and tested on test.wasdi.net
