### ISSUE TITLE
Rotate dockers log

### ISSUE THREAD

**Issue by kr1zz** [fadeoutsoftware/WASDI#332]
Rotate dockers log more often

**Comment by mmenapace** [comment]
Implemented and deployed on CREODIAS-2. Use as reference for other nodes.

**Comment by wasdi-sysadmin-br** [comment]
**Update:** 

I did a quick analysis: the log rotation doesn't work.
Reason - short version: logrotate is badly configured

Reason - long version:
  - logrotate has a crontab under /etc/cron.daily/logrotate
  - but if we analyze the code we can see a condition: in reality logrotate is executed by a SystemD timer
  - when we analyze SystemD logs we can see this error:

```
Dec 20 00:00:33 wasdi-creodias-2 logrotate[977414]: error: error renaming /usr/lib/wasdi/launcher/logs/dockers.log.10 to /usr/lib/wasdi/launcher/logs/dockers.log.11: Read-only file system
```

  - and yet the FS is availble in read-write: the problem is the parameter ProtectSystem=full in /lib/systemd/system/logrotate.service

Fix to test:
  - create an override configuraiton file for /lib/systemd/system/logrotate.service
  - add this:

```
[Service]
ReadWritePaths="/usr/lib/wasdi/launchers/logs"
```

  - to test

**Comment by wasdi-sysadmin-br** [comment]
**Update**

My test failed.

I worked on a new fix which seems work:
- it is deployed everywhere
- I will control tomorrow morning

I profited of the deployment to improve a little bit the configuration for docker by adding these parameters:

```
    compress
    delaycompress
    copytruncate
```

**Comment by wasdi-sysadmin-br** [comment]
**Update**

Step 1 is completed at 90%: I'm just waiting the Paolo's confirmation before to remove old WASDI's configuration files

**Comment by wasdi-sysadmin-br** [comment]
**Update**

For me all problems are fixed.
Now I will ask to Cristiano what he meant by "more often":
  - was it because it didn't work?
  - or because 20 MB of data is too much?
