### ISSUE TITLE
CONDA Docker not working

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#452]
The actual conda docker has different problems.
The main one is that wasdi is installed in the venv and not in the conda env.
The proc server starts in pip python and so does the user processor that does not use the conda env.
Env must be before enabled for the shell and then activated.
wasdi must be installed in than one

**Comment by wasdi-sysadmin-br** [comment]
**Update:**

_The main one is that wasdi is installed in the venv and not in the conda env._
Fixed.

Solution / what I did:
- I removed the virtual environment created with the pip3 command available on the system
- instead of to install pip libraries (wasdi + requests + etc etc) in the virtual environment, I install these libraries using the pip3 command provided by conda

Control made:
1. Connection with the tomcat user

2. Control if the wasdi library is installed:
# /usr/bin/pip3 list | grep -i wasdi
--> not available

3. Control which is the default pip3 command:
# which pip3
/home/wasdi/miniconda/bin/pip3
--> so by default, when connected as tomcat, pip3 is /home/wasdi/miniconda/bin/pip3

4. Control with this default pip3 command if the wasdi library is available:
pip3 list | grep -i wasdi
--> available

5. Control which is the default python commands:
# which python3
/home/wasdi/miniconda/bin/python3

# which python 
/home/wasdi/miniconda/bin/python

6. Test an import of wasdi:
# python3
Python 3.8.12 | **packaged by conda-forge** | (default, Oct 12 2021, 21:59:51) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import wasdi
>>> 
--> no error message

**Comment by wasdi-sysadmin-br** [comment]
**Update:**

We are testing this Dockerfile with Paolo because it seems my changes fix all problems: to confirm.

I worked on the optimization of the image too:
- current Dockerfile in the GIT repository: if we build without the user application/user code, the image size is 4.42 GB
- new Dockerfile I have: 2.09 GB
