### ISSUE TITLE
Runtime error: mosaic_tile_checker failed due to code issue

### ISSUE THREAD

**Issue by kr1zz** [fadeoutsoftware/WASDI#456]
Execution of mosaic_tile_checker failed because Exception: : 'NoneType' object is not iterable

**Comment by pcampanella** [comment]
The problem exists when the mosaic tile does not have the payload.
We can solve the exception but anyway it is not possible to re-run the application because we do not have input params.
If we want to solve in the checker parameter we should add the full default input param to pass to mosaic tile for this cases, changing only the date.
