### ISSUE TITLE
Markdown viewer on app help client -> missing tables

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#478]
It looks that our viewer of the md help file in the marketplace does not shows the tables formatted.

**Comment by mmenapace** [comment]
![image](https://user-images.githubusercontent.com/26542988/155746476-4b5ad2e2-68d3-4ee7-bda3-f07160776db7.png)
The newer versions require an option on the constructor 
`var oConverter = new showdown.Converter({tables: true});`
In the example image no lines are rendered and no backcolor to table cell due to css.
