### ISSUE TITLE
Delete product fails if file already deleted

### ISSUE THREAD

**Issue by kr1zz** [fadeoutsoftware/WASDI#482]
If a file is deleted from the filesystem, but the product is not deleted from the workspace, then WASDI keeps showing the product in the workspace, and the user cannot complete the deletion of the product from the workspace, no matter how many times he/she tries to.

**Comment by ppetrescu-wasdi** [comment]
The deletion failed but due to (multiple) other reasons.

I found and fixed a few bugs that prevented cleaning (of products and/or of workspaces):


1. ProductWorkspaceRepository.deleteByWorkspaceId: the delete filter contained a typo (wokspaceId instead of workspaceId).
For this reason, the associated productWorkspace records/documents were never deleted.
Fixed this bug by correcting the name of the column/property.


2. ProductResource.deleteProduct: NullPointerException caused by failure to retrieve the image.
The record is saved on MongoDb using O.S. paths (sometimes Linux, sometimes Windows) while the search/retrieval was always done using Linux-style paths.

i.e.
C:/Users/PetruPetrescu/.wasdi/petru.petrescu@wasdi.cloud/9543259c-e1e1-4fd4-a3b7-d4e7a18f0a87/S1A_IW_OCN__2SDV_20220630T053654_20220630T053719_043888_053D3F_4449.zip
C:\\Users\\PetruPetrescu\\.wasdi\\petru.petrescu@wasdi.cloud\\9543259c-e1e1-4fd4-a3b7-d4e7a18f0a87\\S1A_IW_OCN__2SDV_20220630T053654_20220630T053719_043888_053D3F_4449.zip

Therefore, for Windows workspaces, the deletion of a product always resulted in NullPointerException.
Fixed this bug by performing a second search (with Windows-style path) in case the first search failed.


3. Due to the same issue (Linux-style path separators in Windows), multiple downloads of the same product was permitted.
This caused problems both at the visual level (the product appeared twice in the list, checking one meant checking both, etc) but also at the MongoDB level.
Fixed this bug by performing a second search (with Windows-style path) in case the first search failed.
