### ISSUE TITLE
Production -> Application images lost. 

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#486]
We lost the app images. These were saved on tomcat folder. Images are served as a stream from tomcat.
Now is searching a folder that does not exists.

Maybe we can just copy the assets folder in the 2 tomcats?
Maybe change the folder?

**Comment by wasdi-sysadmin-br** [comment]
**Update**

I did not write in the ticket but I will resume what I said to Paolo few weeks ago.

For the replication, unfortunately I can't use GlusterFS in this context because it's a dynamic directory: this directory is the result of a Tomcat extraction. GlusterFS is a mountpoint and needs stability / static directory.

I can write a script and rsync datas between both servers but I must admit that it's not my prefered solution :
  - it's async
  - we have to synchronize in both direction
  - we can have side effect if the instance A -> B and B -> A are running at same time: same if we delay the cron it can happen
  - etc

From my memory, I suggested to Paolo 2 things :
  - to change the folder: if we have a static folder I can configure a GlusterFS
  - or to think to a long term solution like an object storage or why not MongoDB or something else
  
For we have to discuss to validate a solution and implement it :)

**Comment by pcampanella** [comment]
@wasdi-sysadmin-br  thanks.
The point is that, when the user wants to see the application, the system generates a link like this:

https://www.wasdi.net/assets/img/processors/listdemo2/logo.png

that at the end is the webaddress + the relative image path.

Before it was under tomcat: now how the proxy routes that path?
Where we should put these images?

**Comment by wasdi-sysadmin-br** [comment]
@pcampanella At this moment Nginx is configured to deliver the content.
It means :
  - it is not a network routing
  - datas are read by Nginx and sent to the user by Nginx

Problem :
  - on a node on which Nginx and Tomcat are installed (example: a computational node) : it works
  - on a node on which Nginx and Tomcat are splitted in many machines (example : main nodes cluster in production) : it failed because Nginx tries to read a data that doesn't exist

The "where" could be many solutions :
  - 1/ if computational nodes don't need the datas we could imagine to store these datas at client level : therefore datas will be read by Nginx in /var/www/wasdi/assets/img/processors/<....>. It means the code to save the datas on disk will be moved in the client.
  - 2/ we could imagine to save them in the MongoDB database waiting a better solution: not a definitive solution if the data volume increases a lot at a time (because we could impact the backup time, etc).
  - 3/ we could imagine to take an object storage bucket somewhere (Amazon, Azure, etc) and store datas in the object storage
  - 4/ we could imagine to have a new directory for these datas replicated with GlusterFS + we could imagine to replicate the directory between the main nodes (load balancer + tomcat nodes). This solution seems "magic" and "perfect" but we will probably start to meet problems with users rights as Nginx is started with a user www-data when Tomcat is started as 'tomcat'. Except if WASDI explicity set the right chmod on the files ;)
  
  My preferred solutions in this order :
  - short term: #2 (MongoDB). But if the volume of datas increases, we will probably have to do something else at a moment.
  - middle term: #3 (object storage)
