### ISSUE TITLE
Wasdi Libraries: add the automatic upload feature in addFileToWASDI

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#53]
As the getFullProductPath has the automatic download, the libraries should implement also the automatic upload to move to the cloud products generated on the client PC.
Add the relative options to the config file.

**Comment by kr1zz** [comment]
I [did it](https://github.com/fadeoutsoftware/WASDI/tree/feature/libAutomaticUpload), or at least I think so: when `getFullProductPath( sProductName)` is called, if the file is on the local file system but not on WASDI, and if uploadActive is true, then the file is automatically uploaded. Is that what you meant, @pcampanella ?
Because we discussed it with @sergin13 and we were not 100% sure we understood what you meant...

**Comment by kr1zz** [comment]
So far, this is done for:
- Java
- Python

**Comment by kr1zz** [comment]
... and missing libs are:

- IDL
- matlab/octave
