### ISSUE TITLE
Cloud cover filter broken for Landsat 8

### ISSUE THREAD

**Issue by kr1zz** [fadeoutsoftware/WASDI#573]
The cloud filter is broken for Landsat 8: it does not work with any provider.

**Comment by kr1zz** [comment]
Actually, it only works when ONDA is selected as a provider

**Comment by ppetrescu-wasdi** [comment]
The L8 cloud filter (for the CREODIAS provider) was not broken, it was never implemented in the first place.

I implemented it, adapting the URL for the request to the CREODIAS syntax (which is different from the ONDA one).

In fact, I needed to change the client\app\config\appconfig.json file because there were some discrepancies (regarding the cloudCoverPercentage term):

appcongig.json
`
"name": "S2",
"indexname": "cloudcoverpercentage",

"name": "PROBAV",
"indexname": "cloudcoverpercentage",

"name": "L8",
"indexname": "cloudCoverPercentage",
`

Java code
`
QueryTranslatorCREODIAS
	String sCloud = "cloudcoverpercentage:[";

QueryTranslatorEODC
	private static final String s_sCLOUDCOVERPERCENTAGE = "cloudcoverpercentage:[";

QueryTranslatorONDA
	if(sQuery.substring(iStart).contains("cloudCoverPercentage")) {
`
