### ISSUE TITLE
Empty pip.txt on computational node

### ISSUE THREAD

**Issue by kr1zz** [fadeoutsoftware/WASDI#586]
We found the file pip.txt empty on a computational node. Why did it happen? Are there other cases?

**Comment by wasdi-sysadmin-br** [comment]
I searched for the blank pip.txt

Except if I mis something, I don't know why the 'pip.txt' was blank only on ADWAISEO-01...
So what will everything that follows is purely theoretical.

Theory 1/3:
  - the file was blank at the source (== on main nodes)
  - then when we deploy on a computational node we have an empty file: it is logic
  ---> I think it is the wrong way: on the main node the pip.txt file is filled and there is no modification since the 03/06/2022

Theory 2/3:
  - the version deployed on ADWAISEO-01 was an old version
  - at a moment we updated the version on the main node + maybe on some computational nodes but not on ADWAISEO-01
  --> the version on ADWAISEO-01 was behind

Theory 3/3:
  - the file pip.txt was not written properly because of a bug. Example: filesystem fullfilled exactly at the time of writing pip.txt
  --> it would be very unlucky but why not

My preferred theory: the 2/3

**How to fix (or at least improve)?**
1/ improve the Dockerfile to change the package installation:
  - today we have a "raw" command line embedded in the Dockerfile
  - I recommend to switch on my script installUserPackage.sh:
  - it is the same script to use for: apt, pip and conda
  --> it means with a similar command (just an argument to change) we are able to install packages
  - if the user package file (example: pip.txt) doesn't exist, we exit with a return code 0
  - if the user package file (example: pip.txt) exists:
    - check the number of line (of course we ignore empty lines):
    - if there is lines:
      - we install packages
      - we exit with the return code of the installation:
        - if the installation worked succesfully we exit with return code 0
        - if the installation failed, we exit with return code different than 0
        ---> the docker build will failed
    - if there is is no line:
      - we exit with return code 0 --> the docker build continues

2/ I continue to think we should:
  - centralize the build on ONE server: example == main node
  - push the builded image in a centralized repository: example == Nexus
  - work with tags to version our images: example == 0.1 -> 0.2 -> 0.3 -> etc
  - deploy on computational node:
    - the image is downloaded from the central repository (instead of: download a zip + build)
    - the instance is started from this downloaded image
    --> we know exactly which version is running: in some cases it will help us to troubleshot problems
