### ISSUE TITLE
Large Download Broken: NGINX configuration issue?

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#60]
Da WASDI è possibile scaricare file. Quando ci sono file molto grossi dopo un po' si interrompe la connessione. 
Nel Workspace FirstWS del mio utente c'è un file chiamato out.tif da 3Gb che riproduce il bug.
A me serve scaricarlo da un client scritto in Java in particolare.
Se mi connetto al server si interrompe sempre quando arriva ad 1.2 Gb byte più byte meno.
Se mi connetto sulla 8080 direttamente a tomcat arrivano tutti e 3 i giga.
Direi quindi che è probabile che sia NGINX a bloccare il trasferimento.

**Comment by kr1zz** [comment]
Also affects zipped-on-the-fly files #85

**Comment by kr1zz** [comment]
So, after extensive testing with @odrasm, we are inclined to think that the issue is due to specific firewall/proxy/NAT rules on the client side. The solution we wish to test is a resumable download manager (must be implemented with the pair server/client). Here are (hopefully) useful resources/potential candidates:

- [tus](https://tus.io/blog.html): efficient, clean and modern, though it solves the problem of uploading, not downloading. Unless a tus server can be encapsulated in the client, which I doubt. I want leave it here anyway for future reference.
- (to be continued...)

**Comment by kr1zz** [comment]
Posted [here](https://stackoverflow.com/questions/54768273/serve-large-files-for-download-connection-reset-java-jersey-http) for help

**Comment by kr1zz** [comment]
# related issues:

- #85 
- #95 
- #96

**Comment by kr1zz** [comment]
After adding the [Content-Length](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Length) header the issue seems to have disappeared.

tested with:

- [x] Google Chrome Version Version 72.0.3626.119 (Official Build) (64-bit)
- [x] Firefox 
- [x] Opera 58.0.3135.68
- [x] Microsoft Edge 44.17763.1.0
- [x] Microsoft Internet Explorer 11.316.17763.0
