### ISSUE TITLE
Jupyter Notebook: docker-compose ask confirmation in case of docker image rebuild

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#603]
We had to force the re-creation of the docker image to update the wasdi library.
After this step, when trying to generate a new notebook, the system blocked: from logs we have seen that the block was in the docker-compose up command, because the utility made a question waiting for yN answer.

Is possible to avoid this question?
Otherwise we will need a manual start when we will update the image...

**Comment by wasdi-sysadmin-br** [comment]
@pcampanella 

Vocabulary:
  - JN == Jupyter Notebook

I tried to reproduce the problem but without success.

Details of what I did:

1. Creation of a workspace

2. Reconfiguration to move it on TEST-ADWAISEO-02

3. I created a JN by clicking on the button in WASDI:
  - it worked

4. I stopped the container manually:

```
# docker stop <container ID>
```

5. I clicked on the button in WASDI:
  - it worked: WASDI restarted a JN instance

6. I stopped the container manually:

```
# docker stop <container ID>
```

7. I changed something in the template docker-compose.yml.j2

8. I clicked on the button in WASDI:
  - it worked:
    - WASDI restarted a JN instance
    - I have seen the change introduced in the template docker-compose.yml.j2

9. I tried to delete docker image:

```
# docker image rm wasdi/jupyter-notebook:latest
```

```
# docker image rm wasdi/jupyter-notebook:0.3.1
```

-> it failed because wasdi/jupyter-notebook:0.3.1 was in use

10. I stopped the container manually:

```
# docker stop <container ID>
```

11. I deleted all containers that used the image:

```
# docker rm <container ID>
```

12. I deleted the image:

```
# docker image rm wasdi/jupyter-notebook:0.3.1
Untagged: wasdi/jupyter-notebook:0.3.1
Deleted: sha256:b33b4dbd6afe4266ee1781f6f20a8696af16fa35fe50b1948ce453de79e6c889
Deleted: sha256:e27a7d79538fd63e54a9b965aca8d77a27ce3adfdbcd4c3f64012f716363e848
Deleted: sha256:27f60188d526a3ed5bf71797201d85de744b33688bb6673c799dfdd6090b2a54
Deleted: sha256:ffc842297934369db2badd2ca18aead4c0dcd11e606fa425094bb20157f2556c
Deleted: sha256:f8b9898c8fd7ad10fc46eb4d1df43767bb90095d698c3504cc705aa3e83abf0a
Deleted: sha256:e503665370a427231a198df8fd92ddc0ba2a8809e610a422f50ae114e091d8fc
Deleted: sha256:85b1a36656d3dfa7ecf87f87cdcf496efba9e9888418bfbff0a66ac3f488087a
Deleted: sha256:133a3ee01853c0092bfa2a4e57432be7c33a7acffc1dc5e02f03c9c4ca9fe28c
Deleted: sha256:811de0ac8a8a47e66d859cf227636fbfcf615f234b5e09e70d376a5a880e963d
Deleted: sha256:949a781068ec708fbc5b31e370be0287f6acc471d250a15c194be7c994999072
Deleted: sha256:a42705ff3e33f2a423dea40baf03bd712126bc83a5e08c1dc7009b7e13f4452b
Deleted: sha256:deba36669dc688a8269f0877a9a26f2ed00f9a0cb570cfe68aff6a2c3f7812d3
Deleted: sha256:e7e706898013f61c9475f860a9f281c815fc7cecd33302916d398dccb8432d51
```

13. I clicked on the button in WASDI:
  - it worked:
    - WASDI restarted a JN instance
    - I was able to open it

14. I did a similar test :
stop container + delete docker images
change a detail in Dockerfile
click in the WASDI interface: it worked

I don't know what was the problem met but at this moment I'm not able to reproduce :/ 

------

Important detail.
With Jupyter Notebook we implemented a new feature: the versioning concept.
The idea is this one:
  - to use the image versions to be able to "update" in a clean way
  - it is not 100% implemented because WASDI should keep a version somewhere in its DB
  - but to update today the idea is this one:
    - update the Dockerfile (of what should be updated)
    - update the version in /data/wasdi/dockertemplate/jupyter-notebook/var/general_common.env
    - next JN will rebuild the image because WASDI will detect the change between the file general_common.env in the dockertemplate directory and the one in the processor directory ;)

I just don't remember if we implemented the feature for an existing JN :/
