### ISSUE TITLE
Workflow - Execute Batch - Error "Set value for nodes"

### ISSUE THREAD

**Issue by pcampanella** [fadeoutsoftware/WASDI#94]
When I try to execute a batch processing I receive an error that looks related on the server side management of the nodes of the chart. It need to be tested and fixed.

**Comment by mmenapace** [comment]
The problem was in the initialization of the input file list on the client side.
Considering single input workflows, on back end a list of file is expected for each elaboration.
Prevously the client appended the input filename on the list, leading to the error for all the consequent calls.
ref commit b35e0b7a

**Comment by mmenapace** [comment]
Merged fix in develop
